### ISSUE TITLE
Fantroll section?

### ISSUE THREAD

**Issue by BamsTheSergal** [QuaternionMark/Homestuck-Quirk-Generator#28]
Hello! i got a suggestion that might be interesting, What about a tab for fantrolls of some popular MSPFA comics? Like Vast Error or  Hackbent, etc!

**Comment by QuaternionMark** [comment]
Both finding and maintaining fan quirks for the site is not something I'm interested in doing unfortunately.

I was at some point planning a system where anyone could create and share new quirks through the site, but I decided against doing that since it would be too much work for something not a lot of people would use.
